### ISSUE TITLE
Tutorial outdated at 4.1

### ISSUE THREAD

**Issue by Hibou57** [HOL-Theorem-Prover/HOL#685] opened 2019-04-01 09:07 UTC
The tutorial says `DEVIDES_ADD` and `DEVIDES_SUB` can be proved by Metis, but it stops after timeout (I waited long). I guess it was OK before but not anymore (proof assistants automation is a lot sensible to updates, I noticed).

This, instead, works fine to prove both lemmas:

    g `!d a b. d divides a /\ d divides b ==> d divides (a+b)`;
    e (rw[divides_def]);
    e (qexists_tac `q + q'`);
    e (rw[]);
    val DIVIDES_ADD = top_thm();
    drop();

    g `!d a b. d divides a /\ d divides b ==> d divides (a-b)`;
    e (rw[divides_def]);
    e (qexists_tac `q - q'`);
    e (rw[]);
    val DIVIDES_SUB = top_thm();
    drop();

(P.S. hope this time I will really have enough time to learn HOL :-p )

**Comment by mn200** [comment] 2019-04-02 02:30
Your proofs are fine, but I can't reproduce the failure in the `metis_tac` versions that you're seeing.  I've just added further checks to make sure that the proofs do work.  Note you also can try
```
   bin/hol < examples/euclid.sml
```
(in the root HOL directory) to also check that the script from the Tutorial is working.

**Comment by mn200** [comment] 2019-04-02 02:33
In fact, the current repository version of HOL already checks these proofs when it builds the Tutorial, so I don't have a commit to add to what's already there.

**Comment by Hibou57** [comment] 2019-04-02 07:12
@mn200 , the version just says “HOL-4 [Kananaskis 12 (stdknl, built Sat Mar 30 18:58:17 2019)]”. It was built from the ZIP archive.

**Comment by mn200** [comment] 2019-04-10 12:06
Thanks for the report, but I will close this without further work as the issue isn't apparent on `master` and that will soon (!) turn into a K-13 release.

**Closed by mn200** 2019-04-10 12:06 UTC
