### ISSUE TITLE
licence of HOL

### ISSUE THREAD

**Issue by thtuerk** [HOL-Theorem-Prover/HOL#559] opened 2018-06-30 09:10 UTC
Recently the subject of the license of HOL 4 and files distributed with it was brought up by @marioxcc several times. As I understand it, he believes the current license statement is not sufficient and a header in each file is needed (see #485). As a result, he placed copyright notices in `Conv.sml`, `res_quanLib.sml` and `res_quanScript.sml`. Currently the issue is becoming hot as part of pull request #550, which contains such a copyright notice for `BasicProvers.sml`.

I believe @marioxcc is wrong and the current practice of having a central copyright notice is sufficient. However, even if he is right, it is not his decision to change the copyright of HOL 4 and add copyright notices like the following to central files of HOL:

````
(* This file as a whole is assumed to be under the license in the file
"COPYRIGHT" in the HOL4 distribution (note added by Mario Castelán         UOK
Castro).

For the avoidance of legal uncertainty, I (Mario Castelán Castro) hereby   UOK
place my modifications to this file in the public domain per the Creative
Commons CC0 1.0 public domain dedication <https://creativecommons.org/publ
icdomain/zero/1.0/legalcode>. This should not be interpreted as a personal
endorsement of permissive (non-Copyleft) licenses. *)
````

If he is right (which I daub), we need to add a proper header to all files. I don't like multiple licenses
per file. If the license of HOL 4 is not permissive enough for Mario, I have no problem with him placing his own files in the example directory under a different license. However changing the license on parts of the core files in unacceptable for me. 

What to do about the license should in my opinion not be a decision by a single contributor, but be taken by the main developers foremost @mn200 and @konrad-slind and preferably after a discussion in the HOL 4 community. It have so far not heard of such a decision or discussion (please tell me if I missed something). That's why I start this issue.

I see the following options;

- we keep the copyright as it is
- we add a short copyright header to __all__ files

In any case, I would remove the copyright notices by @marioxcc. He should of course be listed as an author, but not put his own contributions to certain files under a different license. If this means removing this contributions, this would be regrettable, but for me a price worth paying.

I would appreciate, if the main authors @mn200, @konrad-slind and perhaps some of the very active HOL developers would comment on this issue and tell their opinion about it.

**Comment by jeremydaw** [comment] 2018-06-30 09:44
Hi,

I'm not at present an active developer, but here's my view.

(1) If you contribute to HOL, you accept that your contributions may be 
copied as per the general HOL COPYRIGHT notice

(2) If you contribute to HOL, you accept that your contributions may be
changed by another developer

(3) If you want to grant more extensive copying rights, there seems no 
reason in principle against this, but it's pointless to do this by 
adding a notice to the file, since any other developer may modify the 
file, without granting these more extensive copying rights over his own 
changes (ie, the Mario Castelán Castro copyright notice would only apply 
to Mario's contributions, not to subseqent changes - which would confuse 
users of the file), that is:

(3a) I see the notice referred to in the email "I (Mario Castelán 
Castro) hereby place my modifications to this file"
Since it's not clear what these modifications are, the whole idea is 
totally pointless.

(4) we don't want every source file cluttered with a different copyright 
notice emanating from every developer who has ever changed the file - 
which would be the natural outcome of Mario's approach

Jeremy

**Comment by mn200** [comment] 2018-06-30 13:05
As with PR #550 I cannot resolve this quickly in the near future.  I'm happy for @xrchz and @konrad-slind to come to a verdict in my absence.  The `hol-developers` mailing list may also be a good venue to hold the discussion.

**Comment by marioxcc** [comment] 2018-06-30 17:05
> (3) If you want to grant more extensive copying rights, there seems no reason in principle against this, but it's pointless to do this by adding a notice to the file, since any other developer may modify the file, without granting these more extensive copying rights over his own changes (ie, the Mario Castelán Castro copyright notice would only apply to Mario's contributions, not to subseqent changes - which would confuse users of the file), that is: (3a) I see the notice referred to in the email "I (Mario Castelán Castro) hereby place my modifications to this file" Since it's not clear what these modifications are, the whole idea is totally pointless.

We have `git annotate` for this.

Note that the FSF and the SFLC recommend adding license headers to each file. This was in fact, required by the rules of GNU Savannah when I was an administrator there (and the rule was there before I joined).

**Comment by binghe** [comment] 2018-06-30 18:19
@marioxcc you're still trying to avoid discussing why your name is beside the copyright notices, i.e. the part `I (Mario Castelán Castro) hereby place my modifications to this file`.

I think @jeremydaw has explained the potential issues quite clearly. You have rights to NOT make contributions if you disagree with HOL's current license, either stated explicitly or implicitly for each code file. And if `git` commands could show your actual modifications, isn't your additional note (again, the part with your name) redundant and even confusing?

**Comment by binghe** [comment] 2018-06-30 18:39
I don't buy it.  No matter what the existing license is (given by global LICENSE file), your changes must be under the same one, thus no need to mention specially. If you don't accept this, I suggest HOL maintainers reverting your changes. Only in case you're creating another theorem prover based on HOL4 and as a whole new project you have rights to put your new license notes into the header of each file, which is quite common in projects forking from others.

**Comment by thtuerk** [comment] 2018-06-30 18:45
@marioxcc While - if the full history is available - and you spend a lot of time, it is theoretically possible to figure out what your contributions are, it is in practice not feasible. Especially since I expect that history will be lost at some point (as happens for such long living projects and as happened for HOL in the past). This holds especially if many people would do the same. I completely agree with @jeremydaw that it is just not feasible to figure out what your contributions are in practice.

I believe, HOL's licence is permissive enough for @marioxcc to add stuff under a compatible license. The license does not prohibit this. However, no-one is forcing us to include changes under a different license in the HOL source code. I'm strongly in favor of reverting the changes and rejecting pull requests with a different license in the future.

**Comment by marioxcc** [comment] 2018-06-30 19:04
>  No matter what the existing license is (given by global LICENSE file), your changes must be under the same one

@binghe: There is no legal necessity that my changes are under the same license, because public domain is compatible with the HOL4 license. Moreover, what you are talking about is _my_ work, not yours, and you have no say over what license it is under (of course, you can incorporate them under your own work and release _your changes_ under the license of your choice).

> While - if the full history is available - and you spend a lot of time, it is theoretically possible to figure out what your contributions are, it is in practice not feasible.

@thuerk: It is nonsense to pretend that typing `git blame src/basicProof/BasicProvers.sml` “takes a lot of time” and “is not feasible”.

> However, no-one is forcing us to include changes under a different license in the HOL source code.

Correct, and also I am under no obligation to contribute my patches and tactics upstream. **I take the time and effort to do so with the intention they will be useful for other users. I find it perplexing that I would face objection for making sure that my changes are available as free software.**

> Especially since I expect that history will be lost at some point (as happens for such long living projects and as happened for HOL in the past).

It happened in the past because HOL started decades before distributed version became the de-facto standard for free software projects. Now everyone has a copy of the history, which virtually eliminates that possibility. Also, in the extremely unlikely case the history is unintentionally lost in the future, then the responsibility is on whoever is responsible for its loss, not me. Check Linux and see if they have lost history even once since they started using Git; they have not, despite being a much larger project than HOL4.

**Comment by binghe** [comment] 2018-06-30 23:01
There is no legal necessity to touch copyright stuff at all. Your crankiness on doing these things looks very suspicious to me.

Generally speaking, there's no essential differences between big and small changes - they're both "contributions", after all sometimes a small but smart bugfix with even one character may solve a huge problem.  But if every contributor must put a "compatible" copyright notes to make that fix "free to public", that would sound *ridiculous* even for people who are not legal experts. And this is what you are trying to do, @marioxcc

**Comment by tjark** [comment] 2018-07-01 11:05
I am neither a HOL4 maintainer nor a copyright expert. With that being said, I would like to offer two observations that might, perhaps, help to resolve the debate.

First, if such copyright notices are deemed undesirable in the HOL4 code, I believe for Mario's contributions to be in the public domain it is sufficient that he publishes them **anywhere** with a notice that puts them in the public domain. For instance, he could choose to publish them (note: his contributions only, **not** the entire HOL4 file) independently in a personal Git repository.

Second, once Mario's contributions are in the public domain (e.g., by being published with a suitable notice either as part of HOL4 or elsewhere), I believe the HOL4 project is at liberty to include the code and re-distribute it under its own license. In other words, once the code has been committed with a notice that puts it in the public domain, the HOL4 project is at liberty to remove that notice.

**Comment by thtuerk** [comment] 2018-07-04 19:11
@marioxcc wrote on pull request #550 

> There is no more complexity. The user can simply ignore the fact that some code is in the public domain. The user already has to comply with the HOL4-wide license and having some strictly more permissive code does not alter that.

There is more complexity. The user sees more copyright notices, wonders why they are there, what the difference is and what the apply to. It is confusing. Moreover, it just does not work easily, since one can't easily figure out, what the license applies to. HOL's license is already pretty permissive, I don't see why you insist on having your contributions declared in the public domain as by the creative commons license. Moreover, if you really want you contributions in the public domain, why not do as @tjark suggests?

**Comment by marioxcc** [comment] 2018-07-04 19:51
@tjark: You are factually correct, but those considerations do not solve the problem at hand because there are other considerations with the issue at hand apart from legal protocols.

> First, if such copyright notices are deemed undesirable in the HOL4 code, I believe for Mario's contributions to be in the public domain it is sufficient that he publishes them anywhere with a notice that puts them in the public domain.

In fact, those tactics and several others are under the GNU GPL 3 or later in [my personal repository](https://puszcza.gnu.org.ua/projects/hol-proofs/). I favor Copyleft and disagree with the ever-increasing use of permissive licenses that remain silent about free software values. That is the reason I do not and will not grant permissive licenses for my code. As a compromise for the common good, I have chosen to use public domain –along with a note, that I do not endorse the permissive license– when contributing small changes whenever compatibility with a permissive license is required.

> Second, once Mario's contributions are in the public domain (e.g., by being published with a suitable notice either as part of HOL4 or elsewhere), I believe the HOL4 project would be at liberty to include the code and re-distribute it under its own license.

As far as I am aware:
- There is no legal obligation to preserve my public domain notices.
- You can not redistribute my code under anything but public domain, because you do not own the Copyright for it and therefore you can not grant a Copyright license. But legally you can modify my code and place the resulting derivate work under the license of your choice.

That being said, these notices contain attribution and a personal statement. Deleting them may not be illegal, but would be very uneducated to the author, just like deleting attribution from a public domain work is.

> Moreover, it just does not work easily, since one can't easily figure out, what the license applies to.

@thtuerk: **For the _third_ time,** this is just a matter of running `git blame`. I have to repeat this because you conveniently ignored it the first 2 times. At this point you are simply obstructing my contributions and wasting my time, so let us make things clear: **It is you who wants to change the status quo and thus you bear the burden of justification, not me. I am unconvinced by your arguments and _I will not remove the headers._** If _you_ remove them unilaterally, you bear the burden of justifying your action to @mn200 @xrchz and @SOwens which would offend a contributor and contradict the precedent by @mn200 of accepting several pull requests with these headers and releasing Kananaskis-12.

**Comment by thtuerk** [comment] 2018-07-04 20:10
@marioxcc `git blame` does not do the job. See explanations above.

I don't agree that an accepted pull request alone states a precedent. There was no public discussion, which I try to start in this issue.

@marioxcc Am I understanding you right that you say, you block us from distributing HOL under it's current license?!?

> You can not redistribute my code under anything but public domain, because you do not own the Copyright for it and therefore you can not grant a Copyright license. But legally you can modify my code and place the resulting derivate work under the license of your choice.

So, we need to delete them to use the current license? But you argue against deleting by

> That being said, these notices contain attribution and a personal statement. Deleting them may not be illegal, but would be very uneducated to the author, just like deleting attribution from a public domain work is.

So, you say HOL now need to be distributed in the public domain?

**Comment by binghe** [comment] 2018-07-04 21:43
To HOL maintainers: this is not fun any more. If you still want to go back to an easier life, simply merge PR #563 and reject future PRs from @marioxcc if they contain similar copyright changes on HOL core files. This kind of matters happen sometimes in other open source projects too, but usually the related PR gets rejected at first places.

**Comment by binghe** [comment] 2018-07-04 22:08
I have another idea:

1. the `HOL/COPYRIGHT` covers the copyright of core HOL files, include `Conv.sml`, `bossLib.sml`, etc. and its legal entity is *HOL4 CONTRIBUTORS*, dated 2017;
2. Mario Castelán Castro is part of *HOL4 CONTRIBUTORS*, as he has made some contributions to HOL4, thus by default he has already claimed HOL's default copyrights to all core files;
3. A single person shouldn't claim two different copyrights (HOL's and public domain) to the same file (and the same piece of code in it) at the same year (2017).

Summing all above items together, his previous copyright additions in the year 2017 are conflict with HOL's default copyrights, thus should be removed. His name were implicitly inside *HOL4 CONTRIBUTORS* who owns all HOL core files.  This may provide legal evidences to remove those existing additions and also prevent future(s) if the main copyright file gets updated to the year 2018 and hereafter.

**Comment by jeremydaw** [comment] 2018-07-05 00:34
> 
> That being said, these notices contain attribution and a personal 
> statement. Deleting them may not be illegal, but would be very 
> uneducated to the author, just like deleting attribution from a public 
> domain work is.
> 
It would certainly be justified in the present instance.  Why should you 
alone be entitled to decide whether HOL source files be cluttered with 
individuals' copyright notices?

>     Moreover, it just does not work easily, since one can't easily
>     figure out, what the license applies to.
> 
> @thtuerk <https://github.com/thtuerk>: *For the /third/ time,* this is 
> just a matter of running |git blame|. I have to repeat this because you 
> conveniently ignored it the first 2 times.

Have you ever come across the concept of basic courtesy?  If you 
repeated it a thousand times it wouldn't make it any more true. If you 
explained why it would be adequate to identify your contributions, that 
would be better, and an appropriate response to someone who takes the 
trouble to consider what you have written.

For the record, man git blame shows "Annotates each line in the given 
file with information from the revision which last modified the line"
This is, at best, some slight help towards identifying all contributors 
to a line of code.

> At this point you are simply 
> obstructing my contributions and wasting my time,

Have you considered how much time people have spent reading your posts 
and considering their replies?

> so let us make things 
> clear: *It is you who wants to change the status quo 

What's your basis for saying this?  That something got accepted once 
before?  If that's so significant, surely a good reason to not accept 
something undesirable now.

> and thus you bear 
> the burden of justification, not me. I am unconvinced by your arguments 
> and /I will not remove the headers./* If /you/ remove them unilaterally, 

I've said why I think they are not wanted, and apart from the reference 
to git annotate (similar to git blame, see above), no-one has argued 
specifically against the points I made.

> you bear the burden of justifying your action to @mn200 
> <https://github.com/mn200> @xrchz <https://github.com/xrchz> and @SOwens 
> <https://github.com/SOwens> which would offend a contributor and 
> contradict the precedent by @mn200 <https://github.com/mn200> of 
> accepting several pull requests with these headers and releasing 
> Kananaskis-12.
> 
> —

**Comment by adah1972** [comment] 2018-07-12 00:02
A fact which seemed ignored is that people can basically do **anything** with public-domain material. That included maintainers removing or changing part of his contribution.

If Mario does not want his ‘copyright notice’ to be changed, it basically means he is not contributing to the public domain. His real licence is something like the BSD licence.

**Comment by mn200** [comment] 2018-07-31 07:00
The issue is that our own `COPYRIGHT` file cannot claim copyright over material in the public domain.  

My feeling is that the way forward will be to ask contributors to either accept the licence in the `COPYRIGHT` file (reworded so that it is more explicit that all contributors jointly own the copyright and that Konrad and I are not claiming copyright over everything), and to add their name to a `CONTRIBUTORS` file.  Alternatively, contributors like @marioxcc can choose to put their contributions into the public domain, to make a note that this is being done in the commit itself and to explicitly adjust a file in the repo listing such public domain contributions.

I don't want notices (other than historical ones that predate our proper use of version control, *i.e.* from before roughly 2000) cluttering up the tops of files, and will probably remove as many of these as possible.

**Comment by jeremydaw** [comment] 2018-07-31 13:09
> The issue is that our own |COPYRIGHT| file cannot claim copyright over material in the public domain.
>
It can't claim copyright over all copies of such material, but it can claim copyright over the copy of such material which has been put into the HOL distribution by its creator

> My feeling is that the way forward will be to ask contributors to either accept the licence in the |COPYRIGHT| file 

I think this is already implicit in the manner in which the HOL project is organised, as a collaborative project, with its existing copyright notice (but I'm not objecting to a clarification being made)

> (reworded so that it is more
> explicit that all contributors jointly own the copyright and that Konrad and I are not claiming copyright over everything),

Where is there any suggestion to that effect?

> and to add their name
> to a |CONTRIBUTORS| file. Alternatively, contributors like @marioxcc <https://github.com/marioxcc> can choose to put their contributions into the public domain, to make a note that this is being done in the commit itself and to explicitly adjust a file in the repo listing such public domain contributions.
>
A note in the commit message would actually identify what material is available (also) under different copyright terms.  Even so, such a notice should be brief and not include the contributor telling his own view of various sorts of software licences

> I don't want notices (other than historical ones that predate our proper use of version control, /i.e./ from before roughly 2000) cluttering up the tops of files, and will probably remove as many of these as possible.
>

I fully support this approach

**Comment by thtuerk** [comment] 2018-07-31 17:03
Sounds like a sensible plan. Here a few comments:

> My feeling is that the way forward will be to ask contributors to either accept the licence in the COPYRIGHT file (reworded so that it is more explicit that all contributors jointly own the copyright and that Konrad and I are not claiming copyright over everything), and to add their name to a CONTRIBUTORS file.

Similar to @jeremydaw I also thought this was what the existing [COPYRIGHT](https://github.com/HOL-Theorem-Prover/HOL/blob/master/COPYRIGHT) and
[CONTRIBUTORS](https://github.com/HOL-Theorem-Prover/HOL/blob/master/CONTRIBUTORS) files already state. However, looking at this discussion it seems very sensible to make this very explicit.

> Alternatively, contributors like @marioxcc can choose to put their contributions into the public domain, to make a note that this is being done in the commit itself and to explicitly adjust a file in the repo listing such public domain contributions.

If the contribution is available under both the license in the [COPYRIGHT](https://github.com/HOL-Theorem-Prover/HOL/blob/master/COPYRIGHT) file (short HOL license below) and as public domain, this is fine by me. Similar to @jeremydaw my understanding is that the creator can choose to put a contribution into HOL under the HOL license and at the same time as well in the public domain. I believe, a simple, clean story is important. If a contributor does not want to accept the HOL license, putting the contributions somewhere in an example directory with a different license would be OK for me. However, adding them to the `src` directory or even worse putting only parts of existing files under a different license sounds confusing to me.

> I don't want notices (other than historical ones that predate our proper use of version control, i.e. from before roughly 2000) cluttering up the tops of files, and will probably remove as many of these as possible.

Sounds like a very good thing to do.

**Comment by mn200** [comment] 2018-08-01 00:42
See [this Stanford page](https://fairuse.stanford.edu/overview/public-domain/welcome/) for some discussion of what “public domain” means in the US. In particular, you cannot simultaneously have a copyright on material and have it also be in the public domain. In short, it is in the public domain *iff* no-one has a copyright on it. 

Following the same page, we might claim collectively claim copyright on the collection and assembly of all the constituents that make up the HOL distribution, even if some of the constituent parts are in fact in the public domain.  

You are right that our copyright notice no longer mentions me and Konrad by name; it used to, and I'd forgotten that we'd changed it (in 7f94c91).

**Comment by thtuerk** [comment] 2018-10-18 06:04
What is the status of the license issue? I still believe it is a urgent, very important problem to solve. If it is unclear what the license of HOL is, HOL will become unusable, I fear.

I still have the same opinion as voiced in July. I don't see that Stanford page @mn200  cites contradicts what @jeremydaw and I were saying. Citing @jeremydaw, I believe the essence is

>> The issue is that our own |COPYRIGHT| file cannot claim copyright over material in the public domain.

> It can't claim copyright over all copies of such material, but it can claim copyright over the copy of such material which has been put into the HOL distribution by its creator

So, how to proceed?

**Comment by mn200** [comment] 2018-10-18 22:44
I will proceed as I suggested, and claim copyright over the assembly, even if some components of the assembly are in the public domain.  

We cannot claim copyright over the component individually if it is in the public domain.  (Copyright on one copy, but not another is meaningless.)

**Closed** 2019-02-26 22:47 UTC

**Comment by thtuerk** [comment] 2019-02-28 09:45
The changes look good to me. Thanks.
