### ISSUE TITLE
Strange tactic behavior HOL-k10 vs HOL-k12

### ISSUE THREAD

**Issue by ahmedwaqar** [HOL-Theorem-Prover/HOL#561] opened 2018-07-03 12:40 UTC
I observed a strange behavior of the same tactic in HOL-k10 vs HOL-k12

Consider a proof goal

``?!m. ((m = n) \/ m < n) /\ ((if m < n then f m else a) = x)``

e (CONV_TAC(ONCE_DEPTH_CONV COND_ELIM_CONV));

(* In HOL-k10, the tactic results a desired behavior*)

``?!m. ((m = n) \/ m < n) /\ (~(m < n) \/ (f m = x)) /\ (m < n \/ (a = x))``

(* In HOL-k12, the tactic results *) 

``?!m. ((m = n) \/ m < n) /\ (if m < n then $= (f m) else $= a) x``

**Comment by barakeel** [comment] 2018-07-03 14:35
After analysing HOL-k10 and HOL-k12 code I figured that the unwanted behaviour comes from the use of TB in the COND_ELIM_CONV which only applies a conversion if the term is a boolean. I don't see any reason to do that.

So I propose we use this code instead with TB removed.
 I needed to add PURE_REWRITE_CONV [] to rewrite
(x \/ F to x) and (x /\ T to x)

 val COND_ELIM_CONV =
   TOP_DEPTH_CONV
     (COND_RATOR_CONV ORELSEC
      (fn tm => if same_const (op_of_app tm) COND_t then failwith "fail"
                else COND_RAND_CONV tm) ORELSEC
      COND_ABS_CONV) THENC
   REPEATC ELIM_COND1 THENC
   PURE_REWRITE_CONV []

@ahmedwaqar I let you do the pull request to see if this change breaks any proofs.

**Comment by ahmedwaqar** [comment] 2018-07-04 20:31
Thanks! It worked perfectly. I also created the pull request. Please, let me know if you want me to do anything else.

**Comment by xrchz** [comment] 2018-07-04 21:32
I guess a regression test would be nice for this too, which you could put in `src/1/selftest.sml`

**Comment by xrchz** [comment] 2018-07-04 21:46
I committed a selftest for this but it still fails.

**Comment by ahmedwaqar** [comment] 2018-07-05 04:32
Now, the behavior is bit changed ....

 ``?!m. ((m = n) \/ g m n) /\ ((if g m n then f m else a) = x)``

 e (CONV_TAC(ONCE_DEPTH_CONV COND_ELIM_CONV));

``?!m.
       (g m n ==> ((m = n) \/ T) /\ (f m = x)) /\
       (~g m n ==> ((m = n) \/ F) /\ (a = x))``

Although, it works but still not the same as it was behaving in HOL-k10.

**Comment by xrchz** [comment] 2018-07-05 04:46
Exactly, the test fails. @barakeel's fix apparently does not work as intended. I thought you tested it when you made the pull request?

**Comment by barakeel** [comment] 2018-07-05 18:55
The same unexpected behaviour also appears in other functions in this file. I think the TB check is too much.

val tm = ``?!m. ((m = n) \/ g m n) /\ ((if g m n then f m else a) = x)``;;
SUB_AND_COND_ELIM_CONV tm;
Exception- UNCHANGED raised

``(if g m n then $= (f m) else $= a) x`` is a conditional that should be expanded but the result has type
``:num -> bool`` so TB should also let through this type and many others.

**Comment by barakeel** [comment] 2018-07-05 19:11
Disregard the first part of my previous commet, I forgot to force the result to be of type num.
val tm = “∃!m. ((m = n) ∨ g m n) ∧ ((if g m n then f m else a:num) = x)”: term.

SUB_AND_COND_ELIM_CONV tm;;
val it =
   ⊢ (∃!m. ((m = n) ∨ g m n) ∧ ((if g m n then f m else a) = x)) ⇔
     ∃!m.
         (g m n ⇒ ((m = n) ∨ T) ∧ (f m = x)) ∧
         (¬g m n ⇒ ((m = n) ∨ F) ∧ (a = x)): thm

COND_ELIM_CONV tm;
val it =
   ⊢ (∃!m. ((m = n) ∨ g m n) ∧ ((if g m n then f m else a) = x)) ⇔
     ∃!m. ((m = n) ∨ g m n) ∧ (if g m n then $= (f m) else $= a) x: thm

So probably we only need to remove TB when it's used over COND_RAND_CONV and COND_RATOR_CONV and we should leave it over COND_ABS_CONV.

**Comment by barakeel** [comment] 2018-07-05 19:14
I used the functions from HOL-k12 (before the merge) to create the two previous examples.

**Comment by barakeel** [comment] 2018-07-05 19:16
So I know propose this code, although it has still the drawback of not being exactly like HOL-k10

val new_COND_ELIM_CONV =
TOP_DEPTH_CONV
(COND_RATOR_CONV ORELSEC
(fn tm => if same_const (op_of_app tm) COND_t then failwith "fail"
else COND_RAND_CONV tm) ORELSEC
TB COND_ABS_CONV) THENC
REPEATC ELIM_COND1

new_COND_ELIM_CONV tm;
val it =
   ⊢ (∃!m. ((m = n) ∨ g m n) ∧ ((if g m n then f m else a) = x)) ⇔
     ∃!m.
         (g m n ⇒ ((m = n) ∨ T) ∧ (f m = x)) ∧
         (¬g m n ⇒ ((m = n) ∨ F) ∧ (a = x)): thm

**Comment by barakeel** [comment] 2018-07-05 19:20
I admit I am bit in the dark here, maybe more test characterizing the behaviour of these functions are necessary.

**Comment by xrchz** [comment] 2018-07-05 20:20
What changed between k10 and k12 to make this regression? Is it obvious, or does someone need to try git bisect?

**Comment by barakeel** [comment] 2018-07-05 20:52
v10
val COND_ELIM_CONV =
 let fun op_of_app tm = op_of_app (rator tm) handle _ => tm
 in
 fn tm =>
 TOP_DEPTH_CONV
  (COND_EXPAND_CONV ORELSEC
   COND_RATOR_CONV ORELSEC
   (fn tm => if ((#Name (dest_const (op_of_app tm)) = "COND")
                 handle HOL_ERR _ => false)
             then failwith "fail"
             else COND_RAND_CONV tm) ORELSEC
   COND_ABS_CONV
  )
 tm
 end;

v12
val COND_ELIM_CONV =
   TOP_DEPTH_CONV
     (TB COND_RATOR_CONV ORELSEC
      (fn tm => if same_const (op_of_app tm) COND_t then failwith "fail"
                else TB COND_RAND_CONV tm) ORELSEC
      TB COND_ABS_CONV) THENC
   REPEATC ELIM_COND1

So assuming the underlying tactics didn't change (COND_RATOR_CONV, COND_RAND_CONV and COND_ABS_CONV), we have two new functions added in the new code TB and ELIM_COND1.

**Closed** 2018-07-12 15:46 UTC
